basePath: /
host: localhost:8080
info:
  contact:
    email: support@example.com
    name: API Support
    url: https://example.com/support
  description: API для Valentinka Telegram-бота. Позволяет отправлять сообщения пользователям
    и делать рассылки.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: https://example.com/terms/
  title: ValentinkaBot API
  version: "1.0"
paths: {}
schemes:
- http
- https
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: X-Secret-Key
    type: apiKey
swagger: "2.0"
